// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQCOji2Dzy0U-jrT1GgzTXP-6r-IIHXI8',
    appId: '1:469964694943:web:bc900d36a9390f247209aa',
    messagingSenderId: '469964694943',
    projectId: 'gia-pha-3a17e',
    authDomain: 'gia-pha-3a17e.firebaseapp.com',
    storageBucket: 'gia-pha-3a17e.appspot.com',
    measurementId: 'G-KSYPVT4HXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzG85CFwsk96ytPtBxjoVBHTrdicsa01I',
    appId: '1:469964694943:android:345944c4deb4bf0e7209aa',
    messagingSenderId: '469964694943',
    projectId: 'gia-pha-3a17e',
    storageBucket: 'gia-pha-3a17e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1t7v3lJK_jVc6IhCiIgHtaq84wt2YvQ',
    appId: '1:469964694943:ios:f3194f47a2a770457209aa',
    messagingSenderId: '469964694943',
    projectId: 'gia-pha-3a17e',
    storageBucket: 'gia-pha-3a17e.appspot.com',
    iosBundleId: 'com.example.applicationGiaPha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1t7v3lJK_jVc6IhCiIgHtaq84wt2YvQ',
    appId: '1:469964694943:ios:f3194f47a2a770457209aa',
    messagingSenderId: '469964694943',
    projectId: 'gia-pha-3a17e',
    storageBucket: 'gia-pha-3a17e.appspot.com',
    iosBundleId: 'com.example.applicationGiaPha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQCOji2Dzy0U-jrT1GgzTXP-6r-IIHXI8',
    appId: '1:469964694943:web:6fda98a9f854f2287209aa',
    messagingSenderId: '469964694943',
    projectId: 'gia-pha-3a17e',
    authDomain: 'gia-pha-3a17e.firebaseapp.com',
    storageBucket: 'gia-pha-3a17e.appspot.com',
    measurementId: 'G-QPVBK024T5',
  );
}
